#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


# the tests here are wrong, mulle-craft shouldn't b
run_mulle_template()
{
   if [ "$1" = "--clean-env" ]
   then
      shift

      log_fluff "####################################"
      log_fluff ${MULLE_TEMPLATE} --clean-env ${MULLE_TEMPLATE_FLAGS} "$@"
      log_fluff "####################################"

      exekutor "${MULLE_TEMPLATE}" --clean-env ${MULLE_TEMPLATE_FLAGS} "$@"
   else
      log_fluff "####################################"
      log_fluff ${MULLE_TEMPLATE} ${MULLE_TEMPLATE_FLAGS} "$@"
      log_fluff "####################################"

      exekutor "${MULLE_TEMPLATE}" ${MULLE_TEMPLATE_FLAGS} "$@"
   fi
}


expect()
{
   local expected="$1"
   local filename="$2"

   local result

   if ! result="`cat "${filename}" 2> /dev/null`"
   then
      fail "${filename} does not exist"
   fi

   log_debug "${filename}: ${result}"
   if [ "${expected}" != "${result}" ]
   then
      fail "${filename}: \"${result}\" != \"${expected}\""
   fi
}


main()
{
   MULLE_TEMPLATE_FLAGS="$@"

   _options_mini_main "$@"

   MULLE_TEMPLATE_EXTENSION_PATH="${PWD}"
   export MULLE_TEMPLATE_EXTENSION_PATH

   local directory

   directory="`make_tmp_directory`"
   directory="${directory:-/tmp/build}"

   if run_mulle_template --clean-env -DKEY="-" "template-notthere" "${directory}/output"
   then
      fail "Missing template should be an error"
   fi
   log_warning "Failed as expected"

   if [ -e "${directory}/output" ]
   then
      fail "File should not have been created on error"
   fi

   log_verbose "----- #1 PASSED -----"

   run_mulle_template --clean-env -DKEY="-" "template" "${directory}/output"
   expect "a-z" "${directory}/output"

   log_verbose "----- #2 PASSED -----"

   # should not clobber if already present
   run_mulle_template --clean-env -DKEY="-" "template" "${directory}/output"
   expect "a-z" "${directory}/output"

   log_verbose "----- #3 PASSED -----"

   # but clobbers with force
   run_mulle_template --clean-env -f -DKEY="--" "template" "${directory}/output"
   expect "a--z" "${directory}/output"

   log_verbose "----- #4 PASSED -----"


   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "file" || exit 1

   MULLE_TEMPLATE="${MULLE_TEMPLATE:-${PWD}/../../mulle-template}"
}


init "$@"
main "$@"

